[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "cups", "dbus", "libdrm", "expat", "libxcomposite", "libxdamage", "libxfixes", "libxrandr", "mesa", "libgbm", "alsa-lib", "pango", "cairo", "xorg.libX11", "xorg.libXcomposite", "xorg.libXcursor", "xorg.libXdamage", "xorg.libXext", "xorg.libXi", "xorg.libXrandr", "xorg.libXrender", "xorg.libXtst", "xorg.libxcb", "xorg.libxshmfence", "xorg.libXScrnSaver"]

[phases.install]
cmds = ["cd server && npm install"]
